### ISSUE TITLE
Doc ingestion without config is failing silently

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1192]
```
Could not execute command from {"command"=>"message", "identifier"=>"{\"channel\":\"IngestionChannel\",\"token\":\"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiYzk2ZTg1ODEtZDdjOC00NzI5LWIzMGEtMjI4NDA2OWFmMDIxIiwiZXhwIjoxNTMzNzUzMDkxfQ.V2HjDKlqaDneBICOveHF2krE-atEn8fNNPMuVDiE1kM\",\"ingestion\":\"8df90a63-24a1-4237-ad55-0ae4f4ecf358\"}", "data"=>"{\"action\":\"process\"}"}) [Ingestions::Fetchers::FetchFailed - ["Neither PUB key nor PRIV key: nested asn1 error\napp/services/factory/drive_session.rb:25:in `create_service_account_session'\napp/services/ingestions/fetchers/google_doc.rb:24:in `session'\napp/services/ingestions/fetchers/google_doc.rb:38:in `fetch'\napp/services/ingestions/fetchers/google_doc.rb:6:in `perform'\napp/services/ingestions/fetchers/abstract_fetcher.rb:22:in `block in execute'\napp/services/ingestions/fetchers/abstract_fetcher.rb:21:in `execute'\napp/services/ingestions/concerns/catches_exceptions.rb:22:in `watch_for_uncaught_exceptions!'\napp/services/ingestions/abstract_interaction.rb:13:in `compose'\napp/services/ingestions/fetcher.rb:10:in `execute'\napp/services/ingestions/concerns/catches_exceptions.rb:22:in `watch_for_uncaught_exceptions!'\napp/services/ingestions/context.rb:27:in `maybe_fetch_external_source'\napp/services/ingestions/context.rb:16:in `initialize'\napp/services/ingestions/ingestor.rb:22:in `new'\napp/services/ingestions/ingestor.rb:22:in `context'\napp/models/ingestion.rb:120:in `begin_processing'\napp/channels/ingestion_channel.rb:34:in `process'"]]: /Users/mono/src/manifold/api/app/services/ingestions/context.rb:34:in `handle_fetch_error' | /Users/mono/src/manifold/api/app/services/ingestions/context.rb:29:in `maybe_fetch_external_source' | /Users/mono/src/manifold/api/app/services/ingestions/context.rb:16:in `initialize' | /Users/mono/src/manifold/api/app/services/ingestions/ingestor.rb:22:in `new' | /Users/mono/src/manifold/api/app/services/ingestions/ingestor.rb:22:in `context'
```

This error isn't halting the ingestion process, so it never makes it into the log and the ingestion just hangs.

**Comment by SMaxOwok** [comment]
This is specific to single google doc files when fetch fails in context initialization.
