### ISSUE TITLE
Regression: reingestion is not working

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1294]
I've tried reingesting a couple different texts, and I keep hitting the same error:

Connecting to Manifold websocket...
Ingesting "c96b99b046a9f707b6d662a825698d3f.epub"
Using strategy Epub
Processing failed.

undefined method `id_previously_changed?' for nil:NilClass
app/services/ingestions/compilers/text.rb:42:in `report'
app/services/ingestions/compilers/text.rb:8:in `execute'
app/services/ingestions/concerns/catches_exceptions.rb:22:in `watch_for_uncaught_exceptions!'
app/services/ingestions/abstract_base_interaction.rb:10:in `compose'
app/services/ingestions/abstract_base_interaction.rb:14:in `compose_into'
app/services/ingestions/compiler.rb:24:in `create_text'
app/services/ingestions/compiler.rb:6:in `execute'
app/services/ingestions/concerns/catches_exceptions.rb:22:in `watch_for_uncaught_exceptions!'
app/services/ingestions/abstract_base_interaction.rb:10:in `compose'
app/services/ingestions/abstract_base_interaction.rb:14:in `compose_into'
app/services/ingestions/ingestor.rb:18:in `execute'
app/services/ingestions/concerns/catches_exceptions.rb:22:in `watch_for_uncaught_exceptions!'
app/models/ingestion.rb:118:in `begin_processing'
app/channels/ingestion_channel.rb:34:in `process'

**Comment by zdavis** [comment]
Bug may be specific to EPUB ingestion.
