### ISSUE TITLE
500 error running tweet fetcher on umn instance

### ISSUE THREAD

**Issue by SMaxOwok** [ManifoldScholar/manifold#1479]
Was able to fetch tweet in question locally.  Trying to immediately fetch on UMN threw a 500 error.

```
I, [2018-10-12T21:42:14.744147 #3456]  INFO -- : [a35c97f0-8e52-4bb6-818d-d37d2024b68a] Started POST "/api/v1/twitter_queries/1752d114-b67a-4095-9c4d-a2550c03ec56/relationships/fetch" for 71.236.213.87 at 2018-10-12 21:42:14 +0000
I, [2018-10-12T21:42:14.745529 #3456]  INFO -- : [a35c97f0-8e52-4bb6-818d-d37d2024b68a] Processing by Api::V1::TwitterQueries::Relationships::TwitterQueryFetchController#create as */*
I, [2018-10-12T21:42:14.745615 #3456]  INFO -- : [a35c97f0-8e52-4bb6-818d-d37d2024b68a]   Parameters: {"twitter_query_id"=>"1752d114-b67a-4095-9c4d-a2550c03ec56"}
I, [2018-10-12T21:42:14.971454 #3456]  INFO -- : [a35c97f0-8e52-4bb6-818d-d37d2024b68a] Completed 500 Internal Server Error in 226ms (ActiveRecord: 2.7ms)
F, [2018-10-12T21:42:14.972266 #3456] FATAL -- : [a35c97f0-8e52-4bb6-818d-d37d2024b68a]   
F, [2018-10-12T21:42:14.972383 #3456] FATAL -- : [a35c97f0-8e52-4bb6-818d-d37d2024b68a] TypeError (Can't convert TwitterQuery into String.):
F, [2018-10-12T21:42:14.972459 #3456] FATAL -- : [a35c97f0-8e52-4bb6-818d-d37d2024b68a]   
F, [2018-10-12T21:42:14.972510 #3456] FATAL -- : [a35c97f0-8e52-4bb6-818d-d37d2024b68a] app/services/tweet/fetcher.rb:20:in `fetch_one'
[a35c97f0-8e52-4bb6-818d-d37d2024b68a] app/models/twitter_query.rb:40:in `fetch_now'
[a35c97f0-8e52-4bb6-818d-d37d2024b68a] app/controllers/api/v1/twitter_queries/relationships/twitter_query_fetch_controller.rb:11:in `create'
[a35c97f0-8e52-4bb6-818d-d37d2024b68a] lib/middleware/omniauth_stack.rb:10:in `call'
```

**Comment by SMaxOwok** [comment]
Seems related to 7f40ad939aedb8739ffcc4dfb0b9f0041234d223

**Comment by zdavis** [comment]
Deploying this now.
