### ISSUE TITLE
Project search not working as expected on edge

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1519]
See https://edge.manifoldapp.org/api/v1/projects?filter%5Bkeyword%5D=book&page%5Bnumber%5D=2&page%5Bsize%5D=20

```
I, [2018-10-24T18:54:54.712959 #13768]  INFO -- : [ac5276e1-1312-4312-affd-69c3db4befad] Started GET "/api/v1/projects?filter%5Bkeyword%5D=book&page%5Bnumber%5D=2&page%5Bsize%5D=20" for 198.144.157.82 at 2018-10-24 18:54:54 -0700
I, [2018-10-24T18:54:54.798678 #13768]  INFO -- : [ac5276e1-1312-4312-affd-69c3db4befad] Processing by Api::V1::ProjectsController#index as HTML
I, [2018-10-24T18:54:54.799068 #13768]  INFO -- : [ac5276e1-1312-4312-affd-69c3db4befad]   Parameters: {"filter"=>{"keyword"=>"book"}, "page"=>{"number"=>"2", "size"=>"20"}}
I, [2018-10-24T18:54:55.031899 #13768]  INFO -- : [ac5276e1-1312-4312-affd-69c3db4befad] Completed 500 Internal Server Error in 232ms (Searchkick: 40.9ms | ActiveRecord: 52.1ms)
F, [2018-10-24T18:54:55.034249 #13768] FATAL -- : [ac5276e1-1312-4312-affd-69c3db4befad]
F, [2018-10-24T18:54:55.035060 #13768] FATAL -- : [ac5276e1-1312-4312-affd-69c3db4befad] NoMethodError (undefined method `filter_with_query' for #<Searchkick::Results:0x0000564eedf3c630>):
F, [2018-10-24T18:54:55.035225 #13768] FATAL -- : [ac5276e1-1312-4312-affd-69c3db4befad]
F, [2018-10-24T18:54:55.035512 #13768] FATAL -- : [ac5276e1-1312-4312-affd-69c3db4befad] app/models/concerns/filterable.rb:8:in `filter'
[ac5276e1-1312-4312-affd-69c3db4befad] app/models/concerns/filterable.rb:46:in `validate_paginated_results'
[ac5276e1-1312-4312-affd-69c3db4befad] app/models/concerns/filterable.rb:11:in `filter'
[ac5276e1-1312-4312-affd-69c3db4befad] app/controllers/api/v1/projects_controller.rb:20:in `block in <class:ProjectsController>'
[ac5276e1-1312-4312-affd-69c3db4befad] app/controllers/concerns/api/v1/resourceful_methods.rb:45:in `instance_eval'
[ac5276e1-1312-4312-affd-69c3db4befad] app/controllers/concerns/api/v1/resourceful_methods.rb:45:in `load_resources_for'
[ac5276e1-1312-4312-affd-69c3db4befad] app/controllers/concerns/api/v1/resourceful_methods.rb:73:in `load_projects'
[ac5276e1-1312-4312-affd-69c3db4befad] app/controllers/api/v1/projects_controller.rb:28:in `index'
[ac5276e1-1312-4312-affd-69c3db4befad] lib/middleware/omniauth_stack.rb:10:in `call'
^C
```

**Comment by zdavis** [comment]
Noticing other issues on filtering all projects by keyword. If you search for, say, "Tulip," you'll see your results, and then have it revert to an unfiltered list.

**Comment by SMaxOwok** [comment]
This is a very strange issue.  I'm not sure why it isn't replicable locally.

**Comment by zdavis** [comment]
No longer able to reproduce. Appears to be fixed.
