### ISSUE TITLE
Regression in manifold:dev:seed due to event.touch_project!

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#1734]
```
zdavis@gelatinous-cube:~/src/manifold/api$ rails manifold:dev:seed
NOTE: Gem.gunzip is deprecated; use Gem::Util.gunzip instead. It will be removed on or after 2018-12-01.
Gem.gunzip called from /Users/zdavis/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/unicode-display_width-1.3.0/lib/unicode/display_width/index.rb:5.
    INFO: Seeding development environment data
    INFO: Truncate Project table
rails aborted!
ActiveRecord::ActiveRecordError: cannot touch on a new or destroyed record object. Consider using persisted?, new_record?, or destroyed? before touching
/Users/zdavis/src/manifold/api/app/models/event.rb:109:in `touch_project!'
/Users/zdavis/src/manifold/api/app/services/demonstration/data_loader.rb:50:in `block in clear_db'
/Users/zdavis/src/manifold/api/app/services/demonstration/data_loader.rb:48:in `each'
/Users/zdavis/src/manifold/api/app/services/demonstration/data_loader.rb:48:in `clear_db'
/Users/zdavis/src/manifold/api/app/services/demonstration/data_loader.rb:16:in `load'
/Users/zdavis/src/manifold/api/lib/tasks/dev.rake:6:in `block (3 levels) in <top (required)>'
/Users/zdavis/src/manifold/api/bin/rails:9:in `require'
/Users/zdavis/src/manifold/api/bin/rails:9:in `<top (required)>'
/Users/zdavis/src/manifold/api/bin/spring:14:in `<top (required)>'
./bin/rails:3:in `load'
./bin/rails:3:in `<main>'
Tasks: TOP => manifold:dev:seed
(See full trace by running task with --trace)
```

**Comment by SMaxOwok** [comment]
I hit that too, but thought it was from a bad state.
