### ISSUE TITLE
Issues with email on docker installation

### ISSUE THREAD

**Issue by TaylorJadin** [ManifoldScholar/manifold#3584]
I've been playing around with a docker based installation of Manifold, going off the instructions here:
https://manifoldscholar.github.io/manifold-docusaurus/docs/administering/installation#docker-install

I'm running into issues configuring email, though. I've tried using sendmail and SMTP, but whenever I try to use the "Send Test Email" button I get a "500 Error: API Internal Server Error" and no email is sent. Looking at the output of `docker-compose logs -f` I'm noticing this error that seems related:

```
api_rails_1      | F, [2023-04-14T16:20:23.025304 #35] FATAL -- : [0b8a81ab-1723-4f57-8d92-ce9865d853f9]   
api_rails_1      | [0b8a81ab-1723-4f57-8d92-ce9865d853f9] Premailer::Rails::CSSHelper::FileNotFound (File with URL "mail_styles.css" could not be loaded by any strategy.):
api_rails_1      | [0b8a81ab-1723-4f57-8d92-ce9865d853f9]   
api_rails_1      | [0b8a81ab-1723-4f57-8d92-ce9865d853f9] app/models/concerns/recoverable.rb:18:in `send_reset_password_email'
api_rails_1      | [0b8a81ab-1723-4f57-8d92-ce9865d853f9] app/models/concerns/recoverable.rb:14:in `generate_reset_token'
api_rails_1      | [0b8a81ab-1723-4f57-8d92-ce9865d853f9] app/controllers/api/v1/passwords_controller.rb:13:in `create'
api_rails_1      | [0b8a81ab-1723-4f57-8d92-ce9865d853f9] lib/middleware/omniauth_stack.rb:10:in `call'
```

At first, I thought this might be related to my nginx proxy setup, but I've tried it without that, and I'm still seeing the same error, so maybe I'm missing something else here in my setup.

**Comment by zdavis** [comment]
Thanks for reporting this. I'll try to take a look at this over the weekend and see if I can sort it out.

**Comment by stevegiessler** [comment]
I ran into this very issue earlier today and was able to resolve it by exec-ing into the main rails container:

docker exec -it manifold-api_rails-1 bash

And once in there:

cd /opt/manifold/api/public
touch mail_styles.css

Then exit out of the container and restart the containers (not sure if that step is actually necessary).

Turns out it just wanted that stylesheet to be present, even if empty. You can see it was looking for that in the logs. Took me a bit to figure out exactly where to put that file...

Also, for me, the "Sendmail" option in the GUI did not work, despite my MTA being configured properly on the host VM. So I tried the SMTP option and sending mail finally worked from the Manifold test mail in the GUI. I am still having another issue with images in the mail message not displaying but that is because I am using a custom Nginx reverse proxy and I just need to work out how to get the static files to load. Anyway, I hope that helps some folks.

**Comment by stevegiessler** [comment]
I ran into this very issue earlier today and was able to resolve it by exec-ing into the main rails container:

docker exec -it manifold-api_rails-1 bash

And once in there:

cd /opt/manifold/api/public
touch mail_styles.css

Then exit out of the container and restart the containers (not sure if that step is actually necessary).

Turns out it just wanted that stylesheet to be present, even if empty. You can see it was looking for that in the logs. Took me a bit to figure out exactly where to put that file...

Also, for me, the "Sendmail" option in the GUI did not work, despite my MTA being configured properly on the host VM. So I tried the SMTP option and sending mail finally worked from the Manifold test mail in the GUI. I am still having another issue with images in the mail message not displaying but that is because I am using a custom Nginx reverse proxy and I just need to work out how to get the static files to load. Anyway, I hope that helps some folks.

**Comment by TaylorJadin** [comment]
@stevegiessler That did the trick for me, thanks!

In my experience this worked without needing to restart the containers:

```
docker exec manifold_api_rails_1 touch /opt/manifold/api/public/mail_styles.css
```

**Comment by zdavis** [comment]
We're taking a look at this as we dig into the recently reported docker issues. Pinging @scryptmouse and @timbot1789.

**Comment by githubber** [comment]
This is still an issue. 

`api_sidekiq-1    | 2025-09-27T05:14:29.919Z 1 TID-1dfh WARN: {"context":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"ActionMailer::MailDeliveryJob","queue":"mailers","args":[{"job_class":"ActionMailer::MailDeliveryJob","job_id":"89d955fd-438f-4e8f-bcbf-cfcfe203fc25","provider_job_id":null,"queue_name":"mailers","priority":null,"arguments":["AccountMailer","email_confirmation","deliver_now",{"args":[{"_aj_globalid":"gid://manifold-api/User/c4652de4-f17d-48cf-befb-efdfdeb353b1"}],"_aj_ruby2_keywords":["args"]}],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2025-09-27T05:13:06Z"}],"retry":true,"jid":"56af9acdf23e6e24a92b0805","created_at":1758949986.999791,"enqueued_at":1758950069.881689,"error_message":"Manifold was unable to send the email. The exception was of the type\n           \"Mail::Sendmail::DeliveryError.\" The message was \"Delivery failed with exitstatus 127: \"/usr/sbin/sendmail -i -f \\\"do-not-reply@manifoldapp.org\\\" -- \\\"example@mac.com\\\"\".\" Double check your\n          configuration.","error_class":"APIExceptions::StandardError","failed_at":1758949987.065425,"retry_count":1,"retried_at":1758950021.044827},"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ActionMailer::MailDeliveryJob\",\"queue\":\"mailers\",\"args\":[{\"job_class\":\"ActionMailer::MailDeliveryJob\",\"job_id\":\"89d955fd-438f-4e8f-bcbf-cfcfe203fc25\",\"provider_job_id\":null,\"queue_name\":\"mailers\",\"priority\":null,\"arguments\":[\"AccountMailer\",\"email_confirmation\",\"deliver_now\",{\"args\":[{\"_aj_globalid\":\"gid://manifold-api/User/c4652de4-f17d-48cf-befb-efdfdeb353b1\"}],\"_aj_ruby2_keywords\":[\"args\"]}],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2025-09-27T05:13:06Z\"}],\"retry\":true,\"jid\":\"56af9acdf23e6e24a92b0805\",\"created_at\":1758949986.999791,\"enqueued_at\":1758950069.881689,\"error_message\":\"Manifold was unable to send the email. The exception was of the type\\n           \\\"Mail::Sendmail::DeliveryError.\\\" The message was \\\"Delivery failed with exitstatus 127: \\\"/usr/sbin/sendmail -i -f \\\\\\\"do-not-reply@manifoldapp.org\\\\\\\" -- \\\\\\\"example@mac.com\\\\\\\"\\\".\\\" Double check your\\n          configuration.\",\"error_class\":\"APIExceptions::StandardError\",\"failed_at\":1758949987.065425,\"retry_count\":1,\"retried_at\":1758950021.044827}"}
api_sidekiq-1    | 2025-09-27T05:14:29.919Z 1 TID-1dfh WARN: APIExceptions::StandardError: Manifold was unable to send the email. The exception was of the type
api_sidekiq-1    |            "Mail::Sendmail::DeliveryError." The message was "Delivery failed with exitstatus 127: "/usr/sbin/sendmail -i -f \"do-not-reply@manifoldapp.org\" -- \"example@mac.com\""." Double check your
api_sidekiq-1    |           configuration.
api_sidekiq-1    | 2025-09-27T05:14:29.919Z 1 TID-1dfh WARN: /opt/manifold/api/lib/dynamic_mailer/mailer.rb:39:in `handle_exception'
api_sidekiq-1    | /opt/manifold/api/lib/dynamic_mailer/mailer.rb:17:in `rescue in deliver!'
api_sidekiq-1    | /opt/manifold/api/lib/dynamic_mailer/mailer.rb:9:in `deliver!'
api_sidekiq-1    | /usr/local/bundle/gems/mail-2.8.1/lib/mail/message.rb:2145:in `do_delivery'
api_sidekiq-1    | /usr/local/bundle/gems/mail-2.8.1/lib/mail/message.rb:253:in `block in deliver'
api_sidekiq-1    | /usr/local/bundle/gems/actionmailer-6.1.7.3/lib/action_mailer/base.rb:559:in `block in deliver_mail'
api_sidekiq-1    | /usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `block in instrument'
api_sidekiq-1    | /usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
api_sidekiq-1    | /usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `instrument'
api_sidekiq-1    | /usr/local/bundle/gems/actionmailer-6.1.7.3/lib/action_mailer/base.rb:557:in `deliver_mail'
api_sidekiq-1    | /usr/local/bundle/gems/mail-2.8.1/lib/mail/message.rb:253:in `deliver'
api_sidekiq-1    | /usr/local/bundle/gems/actionmailer-6.1.7.3/lib/action_mailer/message_delivery.rb:119:in `block in deliver_now'
api_sidekiq-1    | /usr/local/bundle/gems/actionmailer-6.1.7.3/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
api_sidekiq-1    | /usr/local/bundle/gems/actionmailer-6.1.7.3/lib/action_mailer/message_delivery.rb:118:in `deliver_now'
api_sidekiq-1    | /usr/local/bundle/gems/actionmailer-6.1.7.3/lib/action_mailer/mail_delivery_job.rb:23:in `perform'
`
Which configuration do I check -> Double check your configuration.  ?? docker-compose.yml or manifold.env, or rails.env??  Thi is the same as OP. Installed following https://manifoldscholar.github.io/manifold-docusaurus/docs/administering/installation using the Docker option.

Trying to just make an admin user fails when using `docker exec -it manifold-docker-compose-api_rails-1 \
rails manifold:user:create:admin['email@example.com','test123!','First','Last']`
zsh: no matches found: manifold:user:create:admin['email@example.com','test123!','First','Last']`
